//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public device()
        {
            this.device_status = new HashSet<device_status>();
        }
    
        public Nullable<int> device_type { get; set; }
        public string device_name { get; set; }
        public string device_no { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<device_status> device_status { get; set; }
    }
}
