//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public string file_info { get; set; }
        public Nullable<int> card_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string card_number { get; set; }
        public byte[] expiration_month { get; set; }
        public byte[] expiration_year { get; set; }
        public string csv { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> merchant_id { get; set; }
    
        public virtual merchant merchant { get; set; }
    }
}
