//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public Nullable<int> flag { get; set; }
        public int id { get; set; }
    
        //public virtual ICollection<token> tokens { get; set; }
        //public virtual ICollection<merchant> merchants { get; set; }
    }
}
