//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class card_processingEntities2 : DbContext
    {
        public card_processingEntities2()
            : base("name=card_processingEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<device_status> device_status { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<master> masters { get; set; }
        public virtual DbSet<merchant_type> merchant_type { get; set; }
        public virtual DbSet<merchant> merchants { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<token> tokens { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
