//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class parameter
    {
        public int id { get; set; }
        public string param_name { get; set; }
        public string param_value { get; set; }
        public string param_type { get; set; }
        public Nullable<int> param_status { get; set; }
    }
}
